port: "8000"

db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

notification:
  pathToTheMessage: "cmd/message.html"
  email: "nemurovartem8@gmail.com"